#!/bin/bash

echo "🚀 正在部署她财 (Her-Wealth) 到 Vercel..."
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1️⃣  访问以下链接："
echo "   https://vercel.com/new"
echo ""
echo "2️⃣  点击 'Import Git Repository'"
echo ""
echo "3️⃣  选择 GitHub 仓库：yanhuicsdn/her-wealth"
echo ""
echo "4️⃣  点击 'Deploy' 按钮"
echo ""
echo "5️⃣  等待 2-3 分钟..."
echo ""
echo "6️⃣  完成！你会获得一个免费的 .vercel.app 网址"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "或者直接点击这个一键部署链接："
echo ""
echo "🔗 https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fyanhuicsdn%2Fher-wealth"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 提示："
echo "• 完全免费"
echo "• 支持所有功能（包括 API 路由）"
echo "• 自动 HTTPS"
echo "• 全球 CDN"
echo "• 每次推送到 main 分支都会自动重新部署"
echo ""
